name: hoot-toolkit
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip==22.1.2
  - pip:
    - attrs==22.1.0
    - click==8.1.3
    - dacite==1.6.0
    - opencv-python==4.5.5.*
    - pycocotools==2.0.5
    - requests==2.28.1
    - tqdm==4.64.0


